<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            // Popular countries (requested)
            [
                'name' => 'United Kingdom',
                'ar_name' => 'المملكة المتحدة',
                'country_code' => 'GB',
                'currency_code' => 'GBP',
                'phone_code' => '+44',
                'capital' => 'London',
                'continent' => 'Europe',
                'description' => 'The UK is a leading destination for English language studies with a rich academic heritage.',
                'ar_description' => 'المملكة المتحدة من أبرز الوجهات لدراسة اللغة الإنجليزية وتتميز بتاريخ أكاديمي عريق.',
                'is_popular' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'United States',
                'ar_name' => 'الولايات المتحدة',
                'country_code' => 'US',
                'currency_code' => 'USD',
                'phone_code' => '+1',
                'capital' => 'Washington, D.C.',
                'continent' => 'North America',
                'description' => 'The USA offers diverse English programs across world-class institutions.',
                'ar_description' => 'الولايات المتحدة تقدم برامج إنجليزية متنوعة عبر مؤسسات عالمية المستوى.',
                'is_popular' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'Australia',
                'ar_name' => 'أستراليا',
                'country_code' => 'AU',
                'currency_code' => 'AUD',
                'phone_code' => '+61',
                'capital' => 'Canberra',
                'continent' => 'Oceania',
                'description' => 'Australia combines high-quality education with a vibrant lifestyle.',
                'ar_description' => 'أستراليا تجمع بين التعليم عالي الجودة ونمط حياة حيوي.',
                'is_popular' => true,
                'display_order' => 3,
            ],
            [
                'name' => 'New Zealand',
                'ar_name' => 'نيوزيلندا',
                'country_code' => 'NZ',
                'currency_code' => 'NZD',
                'phone_code' => '+64',
                'capital' => 'Wellington',
                'continent' => 'Oceania',
                'description' => 'New Zealand is known for safe cities and excellent English programs.',
                'ar_description' => 'نيوزيلندا معروفة بمدن آمنة وبرامج إنجليزية ممتازة.',
                'is_popular' => true,
                'display_order' => 4,
            ],
            [
                'name' => 'Canada',
                'ar_name' => 'كندا',
                'country_code' => 'CA',
                'currency_code' => 'CAD',
                'phone_code' => '+1',
                'capital' => 'Ottawa',
                'continent' => 'North America',
                'description' => 'Canada is a popular choice for English studies with friendly multicultural cities.',
                'ar_description' => 'كندا خيار شائع لدراسة الإنجليزية بمدن متعددة الثقافات.',
                'is_popular' => true,
                'display_order' => 5,
            ],
            [
                'name' => 'Cyprus',
                'ar_name' => 'قبرص',
                'country_code' => 'CY',
                'currency_code' => 'EUR',
                'phone_code' => '+357',
                'capital' => 'Nicosia',
                'continent' => 'Europe',
                'description' => 'Cyprus offers a warm climate and affordable language programs.',
                'ar_description' => 'قبرص توفر مناخا دافئا وبرامج لغوية ميسورة.',
                'is_popular' => true,
                'display_order' => 6,
            ],
            [
                'name' => 'Hungary',
                'ar_name' => 'المجر',
                'country_code' => 'HU',
                'currency_code' => 'HUF',
                'phone_code' => '+36',
                'capital' => 'Budapest',
                'continent' => 'Europe',
                'description' => 'Hungary is an affordable destination with growing English programs.',
                'ar_description' => 'المجر وجهة ميسورة مع برامج إنجليزية متنامية.',
                'is_popular' => true,
                'display_order' => 7,
            ],
            [
                'name' => 'Germany',
                'ar_name' => 'ألمانيا',
                'country_code' => 'DE',
                'currency_code' => 'EUR',
                'phone_code' => '+49',
                'capital' => 'Berlin',
                'continent' => 'Europe',
                'description' => 'Germany offers high-quality education and international study options.',
                'ar_description' => 'ألمانيا تقدم تعليما عالي الجودة وخيارات دراسة دولية.',
                'is_popular' => true,
                'display_order' => 8,
            ],
            [
                'name' => 'Ireland',
                'ar_name' => 'إيرلندا',
                'country_code' => 'IE',
                'currency_code' => 'EUR',
                'phone_code' => '+353',
                'capital' => 'Dublin',
                'continent' => 'Europe',
                'description' => 'Ireland is a leading English-speaking destination with welcoming communities.',
                'ar_description' => 'إيرلندا وجهة ناطقة بالإنجليزية مع مجتمع مرحب.',
                'is_popular' => true,
                'display_order' => 9,
            ],
            [
                'name' => 'Malaysia',
                'ar_name' => 'ماليزيا',
                'country_code' => 'MY',
                'currency_code' => 'MYR',
                'phone_code' => '+60',
                'capital' => 'Kuala Lumpur',
                'continent' => 'Asia',
                'description' => 'Malaysia is a budget-friendly destination with modern education hubs.',
                'ar_description' => 'ماليزيا وجهة مناسبة من حيث التكلفة مع مراكز تعليم حديثة.',
                'is_popular' => true,
                'display_order' => 10,
            ],
            [
                'name' => 'Saudi Arabia',
                'ar_name' => 'المملكة العربية السعودية',
                'country_code' => 'SA',
                'currency_code' => 'SAR',
                'phone_code' => '+966',
                'capital' => 'Riyadh',
                'continent' => 'Asia',
                'description' => 'Saudi Arabia is a key market with growing demand for English education.',
                'ar_description' => 'السعودية سوق مهم مع طلب متزايد على تعليم الإنجليزية.',
                'is_popular' => true,
                'display_order' => 11,
            ],
            [
                'name' => 'Bangladesh',
                'ar_name' => 'بنغلاديش',
                'country_code' => 'BD',
                'currency_code' => 'BDT',
                'phone_code' => '+880',
                'capital' => 'Dhaka',
                'continent' => 'Asia',
                'description' => 'Bangladesh offers a large student base seeking international education.',
                'ar_description' => 'بنغلاديش تضم قاعدة طلابية كبيرة تهتم بالتعليم الدولي.',
                'is_popular' => true,
                'display_order' => 12,
            ],
            [
                'name' => 'India',
                'ar_name' => 'الهند',
                'country_code' => 'IN',
                'currency_code' => 'INR',
                'phone_code' => '+91',
                'capital' => 'New Delhi',
                'continent' => 'Asia',
                'description' => 'India is a major source market for English studies abroad.',
                'ar_description' => 'الهند سوق رئيسي لدراسة الإنجليزية في الخارج.',
                'is_popular' => true,
                'display_order' => 13,
            ],
            [
                'name' => 'Pakistan',
                'ar_name' => 'باكستان',
                'country_code' => 'PK',
                'currency_code' => 'PKR',
                'phone_code' => '+92',
                'capital' => 'Islamabad',
                'continent' => 'Asia',
                'description' => 'Pakistan has strong interest in international English programs.',
                'ar_description' => 'باكستان لديها اهتمام قوي ببرامج الإنجليزية الدولية.',
                'is_popular' => true,
                'display_order' => 14,
            ],
            [
                'name' => 'United Arab Emirates',
                'ar_name' => 'الإمارات العربية المتحدة',
                'country_code' => 'AE',
                'currency_code' => 'AED',
                'phone_code' => '+971',
                'capital' => 'Abu Dhabi',
                'continent' => 'Asia',
                'description' => 'The UAE is a regional hub with strong demand for education services.',
                'ar_description' => 'الإمارات مركز إقليمي مع طلب قوي على خدمات التعليم.',
                'is_popular' => true,
                'display_order' => 15,
            ],
            [
                'name' => 'China',
                'ar_name' => 'الصين',
                'country_code' => 'CN',
                'currency_code' => 'CNY',
                'phone_code' => '+86',
                'capital' => 'Beijing',
                'continent' => 'Asia',
                'description' => 'China is a major market for study abroad and English programs.',
                'ar_description' => 'الصين سوق كبير للدراسة بالخارج وبرامج الإنجليزية.',
                'is_popular' => true,
                'display_order' => 16,
            ],
            [
                'name' => 'Bahrain',
                'ar_name' => 'البحرين',
                'country_code' => 'BH',
                'currency_code' => 'BHD',
                'phone_code' => '+973',
                'capital' => 'Manama',
                'continent' => 'Asia',
                'description' => 'Bahrain offers a growing market for international education.',
                'ar_description' => 'البحرين سوق متنامٍ للتعليم الدولي.',
                'is_popular' => true,
                'display_order' => 17,
            ],
            [
                'name' => 'Kuwait',
                'ar_name' => 'الكويت',
                'country_code' => 'KW',
                'currency_code' => 'KWD',
                'phone_code' => '+965',
                'capital' => 'Kuwait City',
                'continent' => 'Asia',
                'description' => 'Kuwait is a key Gulf market with interest in English education.',
                'ar_description' => 'الكويت سوق خليجي مهم يهتم بتعليم الإنجليزية.',
                'is_popular' => true,
                'display_order' => 18,
            ],

            // Additional countries (other continents)
            [
                'name' => 'South Africa',
                'ar_name' => 'جنوب أفريقيا',
                'country_code' => 'ZA',
                'currency_code' => 'ZAR',
                'phone_code' => '+27',
                'capital' => 'Pretoria',
                'continent' => 'Africa',
                'description' => 'South Africa offers affordable English programs and diverse culture.',
                'ar_description' => 'جنوب أفريقيا تقدم برامج إنجليزية ميسورة وثقافة متنوعة.',
                'is_popular' => false,
                'display_order' => 30,
            ],
            [
                'name' => 'Egypt',
                'ar_name' => 'مصر',
                'country_code' => 'EG',
                'currency_code' => 'EGP',
                'phone_code' => '+20',
                'capital' => 'Cairo',
                'continent' => 'Africa',
                'description' => 'Egypt is a key African market with a large student population.',
                'ar_description' => 'مصر سوق أفريقي مهم مع قاعدة طلابية كبيرة.',
                'is_popular' => false,
                'display_order' => 31,
            ],
            [
                'name' => 'Nigeria',
                'ar_name' => 'نيجيريا',
                'country_code' => 'NG',
                'currency_code' => 'NGN',
                'phone_code' => '+234',
                'capital' => 'Abuja',
                'continent' => 'Africa',
                'description' => 'Nigeria has a strong demand for international education opportunities.',
                'ar_description' => 'نيجيريا لديها طلب قوي على فرص التعليم الدولي.',
                'is_popular' => false,
                'display_order' => 32,
            ],
            [
                'name' => 'Kenya',
                'ar_name' => 'كينيا',
                'country_code' => 'KE',
                'currency_code' => 'KES',
                'phone_code' => '+254',
                'capital' => 'Nairobi',
                'continent' => 'Africa',
                'description' => 'Kenya is an emerging market for study abroad.',
                'ar_description' => 'كينيا سوق ناشئ للدراسة بالخارج.',
                'is_popular' => false,
                'display_order' => 33,
            ],
            [
                'name' => 'Brazil',
                'ar_name' => 'البرازيل',
                'country_code' => 'BR',
                'currency_code' => 'BRL',
                'phone_code' => '+55',
                'capital' => 'Brasilia',
                'continent' => 'South America',
                'description' => 'Brazil is a large Latin American market for English education.',
                'ar_description' => 'البرازيل سوق كبير في أمريكا اللاتينية لتعليم الإنجليزية.',
                'is_popular' => false,
                'display_order' => 34,
            ],
            [
                'name' => 'Mexico',
                'ar_name' => 'المكسيك',
                'country_code' => 'MX',
                'currency_code' => 'MXN',
                'phone_code' => '+52',
                'capital' => 'Mexico City',
                'continent' => 'North America',
                'description' => 'Mexico provides a growing base of students seeking English programs.',
                'ar_description' => 'المكسيك توفر قاعدة متنامية من الطلاب الراغبين في برامج الإنجليزية.',
                'is_popular' => false,
                'display_order' => 35,
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['country_code' => $country['country_code']],
                array_merge(
                    [
                        'is_active' => true,
                        'flag' => $country['flag'] ?? null,
                    ],
                    $country
                )
            );
        }
    }
}
