<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageCourseTrainingCourseSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'id' => 1,
                'language_school_id' => 5,
                'branch_id' => 6,
                'course_type_id' => 2,
                'tag_id' => 5,
                'name' => 'Business English Training',
                'ar_name' => 'تدريب الإنجليزية للأعمال',
                'description' => 'Professional English for meetings and presentations.',
                'ar_description' => 'إنجليزية احترافية للاجتماعات والعروض التقديمية.',
                'required_level' => 'B1',
                'study_time' => '20',
                'lessons_per_week' => 20,
                'min_age' => 18,
                'start_date' => 'Monthly',
                'fee_type' => 'weekly',
                'fee_amount' => 260.00,
                'registration_fee' => 60.00,
                'thumbnail' => 'training_courses/business.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 2,
                'language_school_id' => 7,
                'branch_id' => 7,
                'course_type_id' => 2,
                'tag_id' => 1,
                'name' => 'Exam Skills Workshop',
                'ar_name' => 'ورشة مهارات الاختبارات',
                'description' => 'Focused training for IELTS and exam techniques.',
                'ar_description' => 'تدريب مركّز لمهارات IELTS وتقنيات الاختبارات.',
                'required_level' => 'B1',
                'study_time' => '15',
                'lessons_per_week' => 15,
                'min_age' => 18,
                'start_date' => 'Monthly',
                'fee_type' => 'weekly',
                'fee_amount' => 220.00,
                'registration_fee' => 50.00,
                'thumbnail' => 'training_courses/exam-skills.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 3,
                'language_school_id' => 8,
                'branch_id' => 8,
                'course_type_id' => 1,
                'tag_id' => 2,
                'name' => 'Academic Writing Bootcamp',
                'ar_name' => 'معسكر الكتابة الأكاديمية',
                'description' => 'Improve writing structure and clarity.',
                'ar_description' => 'تحسين بنية الكتابة ووضوحها.',
                'required_level' => 'B2',
                'study_time' => '12',
                'lessons_per_week' => 12,
                'min_age' => 18,
                'start_date' => 'Weekly',
                'fee_type' => 'weekly',
                'fee_amount' => 190.00,
                'registration_fee' => 40.00,
                'thumbnail' => 'training_courses/writing.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 4,
                'language_school_id' => 9,
                'branch_id' => null,
                'course_type_id' => 1,
                'tag_id' => 6,
                'name' => 'Teacher Development Course',
                'ar_name' => 'دورة تطوير المعلمين',
                'description' => 'Practical strategies for ESL teachers.',
                'ar_description' => 'استراتيجيات عملية لمعلمي اللغة الإنجليزية.',
                'required_level' => 'B2',
                'study_time' => '10',
                'lessons_per_week' => 10,
                'min_age' => 21,
                'start_date' => 'Quarterly',
                'fee_type' => 'flat',
                'fee_amount' => 650.00,
                'registration_fee' => 0.00,
                'thumbnail' => 'training_courses/teacher.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 5,
                'language_school_id' => 10,
                'branch_id' => 10,
                'course_type_id' => 1,
                'tag_id' => 7,
                'name' => 'Professional Communication Skills',
                'ar_name' => 'مهارات التواصل المهني',
                'description' => 'Speak confidently in professional settings.',
                'ar_description' => 'التحدث بثقة في بيئات العمل.',
                'required_level' => 'B1',
                'study_time' => '16',
                'lessons_per_week' => 16,
                'min_age' => 18,
                'start_date' => 'Monthly',
                'fee_type' => 'weekly',
                'fee_amount' => 210.00,
                'registration_fee' => 45.00,
                'thumbnail' => 'training_courses/communication.jpg',
                'visible' => true,
                'status' => 'published',
            ],
        ];

        foreach ($rows as $row) {
            DB::table('language_course_training_courses')->updateOrInsert(
                ['id' => $row['id']],
                [
                    'language_school_id' => $row['language_school_id'],
                    'branch_id' => $row['branch_id'],
                    'course_type_id' => $row['course_type_id'],
                    'tag_id' => $row['tag_id'],
                    'name' => $row['name'],
                    'ar_name' => $row['ar_name'],
                    'description' => $row['description'],
                    'ar_description' => $row['ar_description'],
                    'required_level' => $row['required_level'],
                    'study_time' => $row['study_time'],
                    'lessons_per_week' => $row['lessons_per_week'],
                    'min_age' => $row['min_age'],
                    'start_date' => $row['start_date'],
                    'fee_type' => $row['fee_type'],
                    'fee_amount' => $row['fee_amount'],
                    'registration_fee' => $row['registration_fee'],
                    'thumbnail' => $row['thumbnail'],
                    'visible' => $row['visible'],
                    'status' => $row['status'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
