<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class LanguageCourseOnlineCourseSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'id' => 1,
                'language_school_id' => 5,
                'course_type_id' => 1,
                'tag_id' => 5,
                'name' => 'General English Online',
                'ar_name' => 'اللغة الإنجليزية العامة أونلاين',
                'description' => 'Build speaking confidence with flexible online lessons.',
                'ar_description' => 'طوّر مهارات التحدث بثقة عبر دروس أونلاين مرنة.',
                'required_level' => 'A1',
                'study_time' => '10',
                'lessons_per_week' => 5,
                'min_age' => 16,
                'start_date' => 'Anytime',
                'fee_type' => 'weekly',
                'fee_amount' => 85.00,
                'currency_code' => 'USD',
                'registration_fee' => 20.00,
                'thumbnail' => 'online_courses/general-english.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 2,
                'language_school_id' => 7,
                'course_type_id' => 2,
                'tag_id' => 1,
                'name' => 'Intensive English Online',
                'ar_name' => 'اللغة الإنجليزية المكثفة أونلاين',
                'description' => 'Accelerate your progress with intensive online classes.',
                'ar_description' => 'سرّع تقدمك بدروس أونلاين مكثفة.',
                'required_level' => 'A2',
                'study_time' => '15',
                'lessons_per_week' => 8,
                'min_age' => 16,
                'start_date' => 'Weekly',
                'fee_type' => 'weekly',
                'fee_amount' => 120.00,
                'currency_code' => 'USD',
                'registration_fee' => 30.00,
                'thumbnail' => 'online_courses/intensive-english.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 3,
                'language_school_id' => 8,
                'course_type_id' => 4,
                'tag_id' => 2,
                'name' => 'IELTS Preparation Online',
                'ar_name' => 'التحضير لاختبار IELTS أونلاين',
                'description' => 'Target all skills with expert IELTS guidance.',
                'ar_description' => 'طوّر جميع المهارات مع إرشاد متخصص لاختبار IELTS.',
                'required_level' => 'B1',
                'study_time' => '12',
                'lessons_per_week' => 6,
                'min_age' => 16,
                'start_date' => 'Monthly',
                'fee_type' => 'weekly',
                'fee_amount' => 135.00,
                'currency_code' => 'USD',
                'registration_fee' => 25.00,
                'thumbnail' => 'online_courses/ielts.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 4,
                'language_school_id' => 9,
                'course_type_id' => 3,
                'tag_id' => 6,
                'name' => 'Semi-Intensive English Online',
                'ar_name' => 'اللغة الإنجليزية شبه المكثفة أونلاين',
                'description' => 'Balanced study plan for steady progress.',
                'ar_description' => 'خطة دراسة متوازنة لتقدم ثابت.',
                'required_level' => 'A2',
                'study_time' => '12',
                'lessons_per_week' => 6,
                'min_age' => 16,
                'start_date' => 'Weekly',
                'fee_type' => 'weekly',
                'fee_amount' => 105.00,
                'currency_code' => 'USD',
                'registration_fee' => 20.00,
                'thumbnail' => 'online_courses/semi-intensive.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 5,
                'language_school_id' => 10,
                'course_type_id' => 1,
                'tag_id' => 7,
                'name' => 'Conversation Club Online',
                'ar_name' => 'نادي المحادثة أونلاين',
                'description' => 'Weekly conversation practice with native tutors.',
                'ar_description' => 'تمارين محادثة أسبوعية مع مدرسين ناطقين أصليين.',
                'required_level' => 'A1',
                'study_time' => '8',
                'lessons_per_week' => 4,
                'min_age' => 16,
                'start_date' => 'Anytime',
                'fee_type' => 'weekly',
                'fee_amount' => 70.00,
                'currency_code' => 'USD',
                'registration_fee' => 15.00,
                'thumbnail' => 'online_courses/conversation.jpg',
                'visible' => true,
                'status' => 'published',
            ],
        ];

        foreach ($rows as $row) {
            DB::table('language_course_online_courses')->updateOrInsert(
                ['id' => $row['id']],
                [
                    'slug' => Str::slug($row['name']) . '-' . $row['id'],
                    'language_school_id' => $row['language_school_id'],
                    'course_type_id' => $row['course_type_id'],
                    'tag_id' => $row['tag_id'],
                    'name' => $row['name'],
                    'ar_name' => $row['ar_name'],
                    'description' => $row['description'],
                    'ar_description' => $row['ar_description'],
                    'required_level' => $row['required_level'],
                    'study_time' => $row['study_time'],
                    'lessons_per_week' => $row['lessons_per_week'],
                    'min_age' => $row['min_age'],
                    'start_date' => $row['start_date'],
                    'fee_type' => $row['fee_type'],
                    'fee_amount' => $row['fee_amount'],
                    'currency_code' => $row['currency_code'],
                    'registration_fee' => $row['registration_fee'],
                    'thumbnail' => $row['thumbnail'],
                    'visible' => $row['visible'],
                    'status' => $row['status'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}

