<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class LanguageCourseSummerCampSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'id' => 1,
                'branch_id' => 6,
                'course_type_id' => 1,
                'tag_id' => 5,
                'name' => 'Coastal English Camp – Brighton',
                'ar_name' => 'مخيم إنجليزي ساحلي – برايتون',
                'description' => 'Morning classes with afternoon beach activities.',
                'ar_description' => 'دروس صباحية مع أنشطة شاطئية بعد الظهر.',
                'required_level' => 'A1',
                'study_time' => '15',
                'lessons_per_week' => 20,
                'age_range' => '13-16 years',
                'start_date' => '2026-06-15',
                'payment_deadline' => '2026-05-15',
                'fee_type' => 'weekly',
                'fee_amount' => 295.00,
                'registration_fee' => 50.00,
                'thumbnail' => 'summer_camps/brighton.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 2,
                'branch_id' => 7,
                'course_type_id' => 1,
                'tag_id' => 1,
                'name' => 'Cambridge University Experience',
                'ar_name' => 'تجربة جامعة كامبريدج',
                'description' => 'Study English while exploring Cambridge.',
                'ar_description' => 'تعلّم الإنجليزية واستكشف مدينة كامبريدج.',
                'required_level' => 'A2',
                'study_time' => '18',
                'lessons_per_week' => 22,
                'age_range' => '16-18 years',
                'start_date' => '2026-07-01',
                'payment_deadline' => '2026-06-01',
                'fee_type' => 'weekly',
                'fee_amount' => 350.00,
                'registration_fee' => 60.00,
                'thumbnail' => 'summer_camps/cambridge.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 3,
                'branch_id' => 8,
                'course_type_id' => 1,
                'tag_id' => 2,
                'name' => 'Oxford Summer English',
                'ar_name' => 'الإنجليزية الصيفية في أكسفورد',
                'description' => 'Cultural trips and immersive lessons.',
                'ar_description' => 'رحلات ثقافية ودروس غامرة.',
                'required_level' => 'A2',
                'study_time' => '16',
                'lessons_per_week' => 20,
                'age_range' => '15-18 years',
                'start_date' => '2026-07-10',
                'payment_deadline' => '2026-06-10',
                'fee_type' => 'weekly',
                'fee_amount' => 340.00,
                'registration_fee' => 55.00,
                'thumbnail' => 'summer_camps/oxford.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 4,
                'branch_id' => 9,
                'course_type_id' => 1,
                'tag_id' => 6,
                'name' => 'London City Discovery Camp',
                'ar_name' => 'مخيم اكتشاف لندن',
                'description' => 'English classes and city tours.',
                'ar_description' => 'دروس إنجليزية مع جولات في المدينة.',
                'required_level' => 'A1',
                'study_time' => '14',
                'lessons_per_week' => 18,
                'age_range' => '12-16 years',
                'start_date' => '2026-08-01',
                'payment_deadline' => '2026-07-01',
                'fee_type' => 'weekly',
                'fee_amount' => 320.00,
                'registration_fee' => 50.00,
                'thumbnail' => 'summer_camps/london.jpg',
                'visible' => true,
                'status' => 'published',
            ],
            [
                'id' => 5,
                'branch_id' => 10,
                'course_type_id' => 1,
                'tag_id' => 7,
                'name' => 'Manchester English Adventure',
                'ar_name' => 'مغامرة الإنجليزية في مانشستر',
                'description' => 'Sports, culture, and English learning.',
                'ar_description' => 'رياضة وثقافة وتعلّم الإنجليزية.',
                'required_level' => 'A1',
                'study_time' => '15',
                'lessons_per_week' => 20,
                'age_range' => '13-17 years',
                'start_date' => '2026-08-10',
                'payment_deadline' => '2026-07-10',
                'fee_type' => 'weekly',
                'fee_amount' => 330.00,
                'registration_fee' => 50.00,
                'thumbnail' => 'summer_camps/manchester.jpg',
                'visible' => true,
                'status' => 'published',
            ],
        ];

        foreach ($rows as $row) {
            DB::table('language_course_summer_camps')->updateOrInsert(
                ['id' => $row['id']],
                [
                    'slug' => Str::slug($row['name']) . '-' . $row['id'],
                    'branch_id' => $row['branch_id'],
                    'course_type_id' => $row['course_type_id'],
                    'tag_id' => $row['tag_id'],
                    'name' => $row['name'],
                    'ar_name' => $row['ar_name'],
                    'description' => $row['description'],
                    'ar_description' => $row['ar_description'],
                    'required_level' => $row['required_level'],
                    'study_time' => $row['study_time'],
                    'lessons_per_week' => $row['lessons_per_week'],
                    'age_range' => $row['age_range'],
                    'start_date' => $row['start_date'],
                    'payment_deadline' => $row['payment_deadline'],
                    'fee_type' => $row['fee_type'],
                    'fee_amount' => $row['fee_amount'],
                    'registration_fee' => $row['registration_fee'],
                    'thumbnail' => $row['thumbnail'],
                    'visible' => $row['visible'],
                    'status' => $row['status'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}

