<?php

namespace Database\Seeders;

use App\Models\SubjectArea;
use App\Models\UniversityCourseCatalog;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class UniversityCourseCatalogSeeder extends Seeder
{
    public function run(): void
    {
        if (! Schema::hasTable('university_course_catalogs')) {
            return;
        }

        $subjectAreas = SubjectArea::query()->get(['id', 'name'])->keyBy('name');

        $courses = [
            ['name' => 'Business & Management', 'ar_name' => 'الأعمال والإدارة'],
            ['name' => 'Risk management', 'ar_name' => 'إدارة المخاطر'],
            ['name' => 'Engineering management', 'ar_name' => 'الإدارة الهندسية'],
            ['name' => 'Banking', 'ar_name' => 'الأعمال المصرفية'],
            ['name' => 'Sustainability Management', 'ar_name' => 'إدارة الاستدامة'],
            ['name' => 'Accounting', 'ar_name' => 'المحاسبة'],
            ['name' => 'Finance', 'ar_name' => 'المالية'],
            ['name' => 'Economics', 'ar_name' => 'الاقتصاد'],
            ['name' => 'Macroeconomics', 'ar_name' => 'الاقتصاد الكلي'],
            ['name' => 'Marketing', 'ar_name' => 'التسويق'],
            ['name' => 'Master of Business Administration MBA', 'ar_name' => 'ماجستير إدارة الأعمال MBA'],
            ['name' => 'Sustainability Studies', 'ar_name' => 'دراسات الاستدامة'],
            ['name' => 'Education', 'ar_name' => 'التعليم'],
            ['name' => 'Law', 'ar_name' => 'القانون'],
            ['name' => 'Politics /Political science', 'ar_name' => 'السياسة / العلوم السياسية'],
            ['name' => 'Journalism', 'ar_name' => 'الصحافة'],
            ['name' => 'Sociology', 'ar_name' => 'علم الاجتماع'],
            ['name' => 'Design and Applied Arts', 'ar_name' => 'التصميم والفنون التطبيقية'],
            ['name' => 'Architecture', 'ar_name' => 'العماره'],
            ['name' => 'Interior Design', 'ar_name' => 'التصميم الداخلي'],
            ['name' => 'Art & Humanities', 'ar_name' => 'الفنون والعلوم الإنسانية'],
            ['name' => 'English Language & Literature / Linguistics', 'ar_name' => 'اللغة الإنجليزية وآدابها / و اللغويات'],
            ['name' => 'History', 'ar_name' => 'التاريخ'],
            ['name' => 'Philosophy', 'ar_name' => 'الفلسفة'],
            ['name' => 'Engineering', 'ar_name' => 'الهندسة'],
            ['name' => 'General Engineering', 'ar_name' => 'الهندسة العامة'],
            ['name' => 'Civil & Structural Engineering', 'ar_name' => 'الهندسة المدنية والإنشائية'],
            ['name' => 'Chemical Engineering', 'ar_name' => 'الهندسة الكيميائية'],
            ['name' => 'Mechanical Engineering', 'ar_name' => 'الهندسة الميكانيكية'],
            ['name' => 'Electrical Engineering', 'ar_name' => 'الهندسة الكهربائية'],
            ['name' => 'Electronics Engineering', 'ar_name' => 'هندسة الإلكترونيات'],
            ['name' => 'Energy engineering', 'ar_name' => 'هندسة الطاقة'],
            ['name' => 'Control, automation, and instrumentation systems engineering', 'ar_name' => 'هندسة أنظمة التحكم والأتمتة والقياس'],
            ['name' => 'Computer & Software Engineering', 'ar_name' => 'هندسة الحاسوب والبرمجيات'],
            ['name' => 'Aerospace & Aviation Systems and Engineering', 'ar_name' => 'هندسة الطيران وأنظمة الطيران'],
            ['name' => 'Mechatronics & Robotics engineering', 'ar_name' => 'هندسة الميكاترونكس / والروبوتات'],
            ['name' => 'Material Engineering & Science', 'ar_name' => 'هندسة المواد / وعلم المواد'],
            ['name' => 'Industrial & Production Engineering', 'ar_name' => 'الهندسة الصناعية والإنتاج'],
            ['name' => 'Biotechnology', 'ar_name' => 'التكنولوجيا الحيوية'],
            ['name' => 'Environmental Engineering', 'ar_name' => 'الهندسة البيئية'],
            ['name' => 'Architectural Engineering', 'ar_name' => 'الهندسة المعمارية'],
            ['name' => 'Biomedical engineering', 'ar_name' => 'الهندسة الطبية الحيوية'],
            ['name' => 'Mining and Mineral engineering', 'ar_name' => 'هندسة التعدين والمعادن'],
            ['name' => 'Marine engineering', 'ar_name' => 'الهندسة البحرية'],
            ['name' => 'Surveying Engineering', 'ar_name' => 'هندسة المساحة'],
            ['name' => 'Urban & Regional Planning', 'ar_name' => 'التخطيط الحضري والإقليمي'],
            ['name' => 'Manufacturing', 'ar_name' => 'التصنيع'],
            ['name' => 'Construction / Construction management and engineering', 'ar_name' => 'البناء / إدارة وهندسة التشييد'],
            ['name' => 'Agriculture & Forestry', 'ar_name' => 'الزراعة / والغابات'],
            ['name' => 'Environmental Sciences', 'ar_name' => 'العلوم البيئية'],
            ['name' => 'Fisheries', 'ar_name' => 'الأسماك'],
            ['name' => 'Veterinary', 'ar_name' => 'الطب البيطري'],
            ['name' => 'Pharmacy & Pharmacology', 'ar_name' => 'الصيدلة وعلم الأدوية'],
            ['name' => 'Sciences & Natural sciences', 'ar_name' => 'العلوم والعلوم الطبيعية'],
            ['name' => 'Biology', 'ar_name' => 'الأحياء'],
            ['name' => 'Chemistry', 'ar_name' => 'الكيمياء'],
            ['name' => 'Physics', 'ar_name' => 'الفيزياء'],
            ['name' => 'Mathematics & Statistics', 'ar_name' => 'الرياضيات والإحصاء'],
            ['name' => 'Earth Sciences & Geology', 'ar_name' => 'الجيولوجيا / و علوم الأرض'],
            ['name' => 'Astronomy', 'ar_name' => 'علم الفلك'],
            ['name' => 'Nanoscience and Nanotechnology', 'ar_name' => 'علم وتقنية النانو'],
            ['name' => 'Computer science', 'ar_name' => 'علوم الحاسب'],
            ['name' => 'Data sciences', 'ar_name' => 'علوم البيانات'],
            ['name' => 'Information and Communication Technologies (ICTs)', 'ar_name' => 'تكنولوجيا المعلومات والاتصالات'],
            ['name' => 'Information security', 'ar_name' => 'أمن المعلومات'],
            ['name' => 'Information systems', 'ar_name' => 'نظم المعلومات'],
            ['name' => 'Information technology', 'ar_name' => 'تكنولوجيا المعلومات'],
            ['name' => 'Services', 'ar_name' => 'الخدمات'],
            ['name' => 'Sports-Related Subjects', 'ar_name' => 'الرياضة وتخصصاتها'],
            ['name' => 'Artificial Intelligence & Machine Learning', 'ar_name' => 'الذكاء الاصطناعي وتعلم الآلة'],
            ['name' => 'Hospitality / Leisure', 'ar_name' => 'الضيافة / الترفيه'],
            ['name' => 'Tour guide / Tour Management', 'ar_name' => ' الإرشاد السياحي / إدارة السياحة'],
            ['name' => 'Heritage resource management', 'ar_name' => 'إدارة موارد التراث'],
            ['name' => 'Nautical sciences', 'ar_name' => 'العلوم البحرية'],
            ['name' => 'Occupational health and safety', 'ar_name' => 'الصحة والسلامة المهنية'],
            ['name' => 'Life Sciences and Medicine', 'ar_name' => 'علوم الحياة والعلوم الطبية'],
            ['name' => 'Religion', 'ar_name' => 'الديانات'],
            ['name' => 'Archaeology', 'ar_name' => 'علم الآثار'],
            ['name' => 'Geography', 'ar_name' => 'الجغرافيا'],
            ['name' => 'Museum studies', 'ar_name' => 'دراسات المتاحف'],
            ['name' => 'Health Sciences', 'ar_name' => 'العلوم الصحية'],
            ['name' => 'Nursing', 'ar_name' => 'التمريض'],
            ['name' => 'Healthcare', 'ar_name' => 'الرعاية الصحية'],
            ['name' => 'Criminology', 'ar_name' => 'علم الجريمة'],
            ['name' => 'Microbiology', 'ar_name' => 'علم الأحياء الدقيقة'],
            ['name' => 'Genetics', 'ar_name' => 'علم الوراثة'],
            ['name' => 'Toxicology', 'ar_name' => 'علم السموم'],
            ['name' => 'Nutrition Sciences', 'ar_name' => 'علوم التغذية'],
            ['name' => 'Science, Technology and Society', 'ar_name' => 'العلوم والتكنولوجيا والمجتمع'],
            ['name' => 'Natural Resources and Conservation', 'ar_name' => 'الموارد الطبيعية والحفظ'],
            ['name' => 'Urban Studies / Affairs', 'ar_name' => 'الدراسات الحضرية / الشؤون الحضرية'],
            ['name' => 'Transportation Studies', 'ar_name' => 'دراسات النقل'],
            ['name' => 'Air Transportation', 'ar_name' => 'النقل الجوي'],
        ];

        $subjectMap = [
            'Business & Management' => 'Business & Management',
            'Risk management' => 'Business & Management',
            'Engineering management' => 'Engineering (General)',
            'Banking' => 'Accounting & Banking',
            'Sustainability Management' => 'Sustainability & Environment',
            'Accounting' => 'Accounting & Banking',
            'Finance' => 'Economics & Finance',
            'Economics' => 'Economics & Finance',
            'Macroeconomics' => 'Economics & Finance',
            'Marketing' => 'Business & Management',
            'Master of Business Administration MBA' => 'Business & Management',
            'Sustainability Studies' => 'Sustainability & Environment',
            'Education' => 'Education',
            'Law' => 'Law',
            'Politics /Political science' => 'Politics & International Relations',
            'Journalism' => 'Journalism & Media',
            'Sociology' => 'Sociology & Social Sciences',
            'Design and Applied Arts' => 'Design & Applied Arts',
            'Architecture' => 'Architecture & Planning',
            'Interior Design' => 'Design & Applied Arts',
            'Art & Humanities' => 'Arts & Humanities',
            'English Language & Literature / Linguistics' => 'English & Linguistics',
            'History' => 'History & Philosophy',
            'Philosophy' => 'History & Philosophy',
            'Engineering' => 'Engineering (General)',
            'General Engineering' => 'Engineering (General)',
            'Civil & Structural Engineering' => 'Civil & Structural Engineering',
            'Chemical Engineering' => 'Chemical & Process Engineering',
            'Mechanical Engineering' => 'Mechanical & Manufacturing Engineering',
            'Electrical Engineering' => 'Electrical & Electronic Engineering',
            'Electronics Engineering' => 'Electrical & Electronic Engineering',
            'Energy engineering' => 'Energy & Environmental Engineering',
            'Control, automation, and instrumentation systems engineering' => 'Electrical & Electronic Engineering',
            'Computer & Software Engineering' => 'Computer & Software Engineering',
            'Aerospace & Aviation Systems and Engineering' => 'Aerospace & Aviation Engineering',
            'Mechatronics & Robotics engineering' => 'Robotics & Mechatronics',
            'Material Engineering & Science' => 'Materials & Industrial Engineering',
            'Industrial & Production Engineering' => 'Materials & Industrial Engineering',
            'Biotechnology' => 'Biotechnology & Biomedical Engineering',
            'Environmental Engineering' => 'Energy & Environmental Engineering',
            'Architectural Engineering' => 'Architecture & Planning',
            'Biomedical engineering' => 'Biotechnology & Biomedical Engineering',
            'Mining and Mineral engineering' => 'Materials & Industrial Engineering',
            'Marine engineering' => 'Marine & Nautical Sciences',
            'Surveying Engineering' => 'Civil & Structural Engineering',
            'Urban & Regional Planning' => 'Urban & Regional Studies',
            'Manufacturing' => 'Materials & Industrial Engineering',
            'Construction / Construction management and engineering' => 'Civil & Structural Engineering',
            'Agriculture & Forestry' => 'Agriculture & Forestry',
            'Environmental Sciences' => 'Environmental Sciences',
            'Fisheries' => 'Marine & Nautical Sciences',
            'Veterinary' => 'Veterinary Sciences',
            'Pharmacy & Pharmacology' => 'Pharmacy & Pharmacology',
            'Sciences & Natural sciences' => 'Natural Sciences',
            'Biology' => 'Biology & Life Sciences',
            'Chemistry' => 'Chemistry',
            'Physics' => 'Physics & Astronomy',
            'Mathematics & Statistics' => 'Mathematics & Statistics',
            'Earth Sciences & Geology' => 'Earth & Geological Sciences',
            'Astronomy' => 'Physics & Astronomy',
            'Nanoscience and Nanotechnology' => 'Physics & Astronomy',
            'Computer science' => 'Computer Science & IT',
            'Data sciences' => 'Data Science & AI',
            'Information and Communication Technologies (ICTs)' => 'Computer Science & IT',
            'Information security' => 'Cyber Security & Information Systems',
            'Information systems' => 'Cyber Security & Information Systems',
            'Information technology' => 'Computer Science & IT',
            'Services' => 'Business & Management',
            'Sports-Related Subjects' => 'Sports Science & Physical Education',
            'Artificial Intelligence & Machine Learning' => 'Data Science & AI',
            'Hospitality / Leisure' => 'Hospitality, Tourism & Leisure',
            'Tour guide / Tour Management' => 'Hospitality, Tourism & Leisure',
            'Heritage resource management' => 'Archaeology & Heritage Studies',
            'Nautical sciences' => 'Marine & Nautical Sciences',
            'Occupational health and safety' => 'Occupational Health & Safety',
            'Life Sciences and Medicine' => 'Health Sciences',
            'Religion' => 'Religion & Theology',
            'Archaeology' => 'Archaeology & Heritage Studies',
            'Geography' => 'Geography',
            'Museum studies' => 'Museum & Cultural Studies',
            'Health Sciences' => 'Health Sciences',
            'Nursing' => 'Nursing & Healthcare',
            'Healthcare' => 'Nursing & Healthcare',
            'Criminology' => 'Criminology & Forensic Studies',
            'Microbiology' => 'Genetics & Microbiology',
            'Genetics' => 'Genetics & Microbiology',
            'Toxicology' => 'Health Sciences',
            'Nutrition Sciences' => 'Nutrition & Food Sciences',
            'Science, Technology and Society' => 'Science, Technology & Society',
            'Natural Resources and Conservation' => 'Sustainability & Environment',
            'Urban Studies / Affairs' => 'Urban & Regional Studies',
            'Transportation Studies' => 'Transportation & Logistics',
            'Air Transportation' => 'Transportation & Logistics',
        ];

        UniversityCourseCatalog::unguard();
        foreach ($courses as $course) {
            $subjectName = $subjectMap[$course['name']] ?? null;
            $subjectId = $subjectName && isset($subjectAreas[$subjectName])
                ? $subjectAreas[$subjectName]->id
                : null;

            $slug = Str::slug($course['name']);

            UniversityCourseCatalog::updateOrCreate(
                ['slug' => $slug],
                [
                    'name' => $course['name'],
                    'ar_name' => $course['ar_name'],
                    'subject_area_id' => $subjectId,
                    'slug' => $slug,
                    'is_active' => true,
                ]
            );
        }
        UniversityCourseCatalog::reguard();
    }
}
