<?php

namespace Database\Seeders;

use App\Models\University;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class UniversitySeeder extends Seeder
{
    public function run(): void
    {
        if (! Schema::hasTable('universities')) {
            return;
        }

        $rows = [
            [
                'id' => 1,
                'name' => 'Imperial College London',
                'slug' => 'imperial-college-london',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1907,
                'website' => 'https://www.imperial.ac.uk',
                'qs_ranking' => 2,
                'the_ranking' => 8,
                'shanghai_ranking' => 26,
                'famous_for' => 'Engineering, Sciences, Medicine, Technology',
                'ar_famous_for' => 'الهندسة، العلوم، الطب، التكنولوجيا',
                'fees' => '£40,000 - £55,000',
                'ar_fees' => 'من 40,000 إلى 55,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 2,
                'name' => 'University of Oxford',
                'slug' => 'university-of-oxford',
                'country_id' => 1,
                'city_id' => 21,
                'type' => 'public',
                'established_year' => 1907,
                'website' => 'https://www.ox.ac.uk',
                'qs_ranking' => 4,
                'the_ranking' => 1,
                'shanghai_ranking' => 6,
                'famous_for' => 'Law, Medicine, Humanities',
                'ar_famous_for' => 'القانون، الطب، العلوم الإنسانية',
                'fees' => '£35,000 - £60,000',
                'ar_fees' => 'من 35,000 إلى 60,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 3,
                'name' => 'University of Cambridge',
                'slug' => 'university-of-cambridge',
                'country_id' => 1,
                'city_id' => 20,
                'type' => 'public',
                'established_year' => 1096,
                'website' => 'https://www.cam.ac.uk',
                'qs_ranking' => 6,
                'the_ranking' => 3,
                'shanghai_ranking' => 4,
                'famous_for' => 'Sciences, Engineering, Mathematics',
                'ar_famous_for' => 'العلوم، الهندسة، الرياضيات',
                'fees' => '£27,000 - £67,000',
                'ar_fees' => 'من 27,000 إلى 67,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 4,
                'name' => 'University College London',
                'slug' => 'university-college-london',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1209,
                'website' => 'https://www.ucl.ac.uk',
                'qs_ranking' => 9,
                'the_ranking' => 22,
                'shanghai_ranking' => 14,
                'famous_for' => 'Medicine, Law, Architecture, Social Sciences',
                'ar_famous_for' => 'الطب، القانون، العمارة، العلوم الاجتماعية',
                'fees' => '£27,000 - £45,000',
                'ar_fees' => 'من 27,000 إلى 45,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 5,
                'name' => "King's College London",
                'slug' => 'kings-college-london',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1836,
                'website' => 'https://www.kcl.ac.uk',
                'qs_ranking' => 31,
                'the_ranking' => 38,
                'shanghai_ranking' => 61,
                'famous_for' => 'Medicine, Law, International Relations',
                'ar_famous_for' => 'الطب، القانون، العلاقات الدولية',
                'fees' => '£25,000 - £50,000',
                'ar_fees' => 'من 25,000 إلى 50,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 6,
                'name' => 'University of Edinburgh',
                'slug' => 'university-of-edinburgh',
                'country_id' => 1,
                'city_id' => 7,
                'type' => 'public',
                'established_year' => 1829,
                'website' => 'https://www.ed.ac.uk',
                'qs_ranking' => 34,
                'the_ranking' => 29,
                'shanghai_ranking' => 37,
                'famous_for' => 'Medicine, Law, Sciences, Literature',
                'ar_famous_for' => 'الطب، القانون، العلوم، الأدب',
                'fees' => '£24,000 - £52,000',
                'ar_fees' => 'من 24,000 إلى 52,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 7,
                'name' => 'University of Manchester',
                'slug' => 'university-of-manchester',
                'country_id' => 1,
                'city_id' => 2,
                'type' => 'public',
                'established_year' => 1583,
                'website' => 'https://www.manchester.ac.uk',
                'qs_ranking' => 35,
                'the_ranking' => 56,
                'shanghai_ranking' => 46,
                'famous_for' => 'Engineering, Business, Computer Science',
                'ar_famous_for' => 'الهندسة، إدارة الأعمال، علوم الحاسوب',
                'fees' => '£25,000 - £52,000',
                'ar_fees' => 'من 25,000 إلى 52,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 8,
                'name' => 'University of Bristol',
                'slug' => 'university-of-bristol',
                'country_id' => 1,
                'city_id' => 8,
                'type' => 'public',
                'established_year' => 2004,
                'website' => 'https://www.bristol.ac.uk',
                'qs_ranking' => 51,
                'the_ranking' => 80,
                'shanghai_ranking' => 98,
                'famous_for' => 'Engineering, Law, Economics, Medicine, Computer Science',
                'ar_famous_for' => 'الهندسة، القانون، الاقتصاد، الطب، علوم الحاسوب',
                'fees' => '£25,000 - £45,000',
                'ar_fees' => 'من 25,000 إلى 45,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 9,
                'name' => 'London School of Economics and Political Science (LSE)',
                'slug' => 'london-school-of-economics-and-political-science',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1909,
                'website' => 'https://www.lse.ac.uk',
                'qs_ranking' => 56,
                'the_ranking' => 52,
                'shanghai_ranking' => 151,
                'famous_for' => 'Economics, Politics, International Relations, Finance, Social Sciences',
                'ar_famous_for' => 'الاقتصاد، السياسة، العلاقات الدولية، المالية، العلوم الاجتماعية',
                'fees' => '£26,000 - £32,000',
                'ar_fees' => 'من 26,000 إلى 32,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 10,
                'name' => 'University of Warwick',
                'slug' => 'university-of-warwick',
                'country_id' => 1,
                'city_id' => 13,
                'type' => 'public',
                'established_year' => 1895,
                'website' => 'https://www.warwick.ac.uk',
                'qs_ranking' => 74,
                'the_ranking' => 122,
                'shanghai_ranking' => 101,
                'famous_for' => 'Business, Management, Economics, Mathematics, Engineering, Computer Science',
                'ar_famous_for' => 'إدارة الأعمال، الإدارة، الاقتصاد، الرياضيات، الهندسة، علوم الحاسوب',
                'fees' => '£25,000 - £38,000',
                'ar_fees' => 'من 25,000 إلى 38,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 11,
                'name' => 'University of Birmingham',
                'slug' => 'university-of-birmingham',
                'country_id' => 1,
                'city_id' => 3,
                'type' => 'public',
                'established_year' => 1965,
                'website' => 'https://www.birmingham.ac.uk',
                'qs_ranking' => 76,
                'the_ranking' => 98,
                'shanghai_ranking' => 151,
                'famous_for' => 'Medicine, Engineering, Business, Law, Education',
                'ar_famous_for' => 'الطب، الهندسة، إدارة الأعمال، القانون، التعليم',
                'fees' => '£22,000 - £38,000',
                'ar_fees' => 'من 22,000 إلى 38,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 12,
                'name' => 'University of Glasgow',
                'slug' => 'university-of-glasgow',
                'country_id' => 1,
                'city_id' => 6,
                'type' => 'public',
                'established_year' => 1900,
                'website' => 'https://www.gla.ac.uk',
                'qs_ranking' => 79,
                'the_ranking' => 84,
                'shanghai_ranking' => 101,
                'famous_for' => 'Medicine, Veterinary Medicine, Engineering, Life Sciences',
                'ar_famous_for' => 'الطب، الطب البيطري، الهندسة، علوم الحياة',
                'fees' => '£23,000 - £45,000',
                'ar_fees' => 'من 23,000 إلى 45,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 13,
                'name' => 'University of Leeds',
                'slug' => 'university-of-leeds',
                'country_id' => 1,
                'city_id' => 5,
                'type' => 'public',
                'established_year' => 1451,
                'website' => 'https://www.leeds.ac.uk',
                'qs_ranking' => 86,
                'the_ranking' => 118,
                'shanghai_ranking' => 151,
                'famous_for' => 'Engineering, Business, Media, Dentistry, Environmental Sciences',
                'ar_famous_for' => 'الهندسة، إدارة الأعمال، الإعلام، طب الأسنان، العلوم البيئية',
                'fees' => '£22,000 - £40,000',
                'ar_fees' => 'من 22,000 إلى 40,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 14,
                'name' => 'University of Southampton',
                'slug' => 'university-of-southampton',
                'country_id' => 1,
                'city_id' => 17,
                'type' => 'public',
                'established_year' => 1904,
                'website' => 'https://www.southampton.ac.uk',
                'qs_ranking' => 87,
                'the_ranking' => 129,
                'shanghai_ranking' => 151,
                'famous_for' => 'Engineering, Computer Science, Marine Science, Business',
                'ar_famous_for' => 'الهندسة، علوم الحاسوب، العلوم البحرية، إدارة الأعمال',
                'fees' => '£23,000 - £42,000',
                'ar_fees' => 'من 23,000 إلى 42,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 15,
                'name' => 'University of Sheffield',
                'slug' => 'university-of-sheffield',
                'country_id' => 1,
                'city_id' => 9,
                'type' => 'public',
                'established_year' => 1952,
                'website' => 'https://www.sheffield.ac.uk',
                'qs_ranking' => 92,
                'the_ranking' => 108,
                'shanghai_ranking' => 151,
                'famous_for' => 'Engineering, Architecture, Journalism, Computer Science',
                'ar_famous_for' => 'الهندسة، العمارة، الصحافة، علوم الحاسوب',
                'fees' => '£22,000 - £40,000',
                'ar_fees' => 'من 22,000 إلى 40,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 16,
                'name' => 'Durham University',
                'slug' => 'durham-university',
                'country_id' => 1,
                'city_id' => 38,
                'type' => 'public',
                'established_year' => 1905,
                'website' => 'https://www.durham.ac.uk',
                'qs_ranking' => 94,
                'the_ranking' => 175,
                'shanghai_ranking' => 201,
                'famous_for' => 'Law, Theology, Politics, Business, Humanities',
                'ar_famous_for' => 'القانون، اللاهوت، السياسة، إدارة الأعمال، العلوم الإنسانية',
                'fees' => '£22,000 - £37,000',
                'ar_fees' => 'من 22,000 إلى 37,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 17,
                'name' => 'University of Nottingham',
                'slug' => 'university-of-nottingham',
                'country_id' => 1,
                'city_id' => 11,
                'type' => 'public',
                'established_year' => 1832,
                'website' => 'https://www.nottingham.ac.uk',
                'qs_ranking' => 97,
                'the_ranking' => 145,
                'shanghai_ranking' => 101,
                'famous_for' => 'Pharmacy, Medicine, Engineering, Business, Agriculture',
                'ar_famous_for' => 'الصيدلة، الطب، الهندسة، إدارة الأعمال، الزراعة',
                'fees' => '£22,000 - £38,000',
                'ar_fees' => 'من 22,000 إلى 38,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 18,
                'name' => 'Queen Mary University of London',
                'slug' => 'queen-mary-university-of-london',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1948,
                'website' => 'https://www.qmul.ac.uk',
                'qs_ranking' => 110,
                'the_ranking' => 134,
                'shanghai_ranking' => 201,
                'famous_for' => 'Law, Medicine, Dentistry, Engineering',
                'ar_famous_for' => 'القانون، الطب، طب الأسنان، الهندسة',
                'fees' => '£21,000 - £38,000',
                'ar_fees' => 'من 21,000 إلى 38,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 19,
                'name' => 'University of St Andrews',
                'slug' => 'university-of-st-andrews',
                'country_id' => 1,
                'city_id' => 56,
                'type' => 'public',
                'established_year' => 1887,
                'website' => 'https://www.st-andrews.ac.uk',
                'qs_ranking' => 113,
                'the_ranking' => 162,
                'shanghai_ranking' => 301,
                'famous_for' => 'International Relations, Philosophy, Economics, Physics',
                'ar_famous_for' => 'العلاقات الدولية، الفلسفة، الاقتصاد، الفيزياء',
                'fees' => '£23,000 - £36,000',
                'ar_fees' => 'من 23,000 إلى 36,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 20,
                'name' => 'University of Bath',
                'slug' => 'university-of-bath',
                'country_id' => 1,
                'city_id' => 22,
                'type' => 'public',
                'established_year' => 1413,
                'website' => 'https://www.bath.ac.uk',
                'qs_ranking' => 132,
                'the_ranking' => 251,
                'shanghai_ranking' => 401,
                'famous_for' => 'Engineering, Architecture, Management, Computer Science',
                'ar_famous_for' => 'الهندسة، العمارة، الإدارة، علوم الحاسوب',
                'fees' => '£23,000 - £39,000',
                'ar_fees' => 'من 23,000 إلى 39,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 21,
                'name' => 'Newcastle University',
                'slug' => 'newcastle-university',
                'country_id' => 1,
                'city_id' => 10,
                'type' => 'public',
                'established_year' => 1966,
                'website' => 'https://www.ncl.ac.uk',
                'qs_ranking' => 137,
                'the_ranking' => 144,
                'shanghai_ranking' => 201,
                'famous_for' => 'Medicine, Architecture, Engineering, Business',
                'ar_famous_for' => 'الطب، العمارة، الهندسة، إدارة الأعمال',
                'fees' => '£21,000 - £37,000',
                'ar_fees' => 'من 21,000 إلى 37,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 22,
                'name' => 'University of Liverpool',
                'slug' => 'university-of-liverpool',
                'country_id' => 1,
                'city_id' => 4,
                'type' => 'public',
                'established_year' => 1963,
                'website' => 'https://www.liverpool.ac.uk',
                'qs_ranking' => 147,
                'the_ranking' => 143,
                'shanghai_ranking' => 101,
                'famous_for' => 'Medicine, Veterinary Science, Engineering, Life Sciences',
                'ar_famous_for' => 'الطب، العلوم البيطرية، الهندسة، علوم الحياة',
                'fees' => '£21,000 - £38,000',
                'ar_fees' => 'من 21,000 إلى 38,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 23,
                'name' => 'University of Exeter',
                'slug' => 'university-of-exeter',
                'country_id' => 1,
                'city_id' => 25,
                'type' => 'public',
                'established_year' => 1903,
                'website' => 'https://www.exeter.ac.uk',
                'qs_ranking' => 155,
                'the_ranking' => 170,
                'shanghai_ranking' => 151,
                'famous_for' => 'Business, Economics, Environmental Science, Psychology',
                'ar_famous_for' => 'إدارة الأعمال، الاقتصاد، العلوم البيئية، علم النفس',
                'fees' => '£22,000 - £35,000',
                'ar_fees' => 'من 22,000 إلى 35,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 24,
                'name' => 'Lancaster University',
                'slug' => 'lancaster-university',
                'country_id' => 1,
                'city_id' => 46,
                'type' => 'public',
                'established_year' => 1955,
                'website' => 'https://www.lancaster.ac.uk',
                'qs_ranking' => 157,
                'the_ranking' => 184,
                'shanghai_ranking' => 301,
                'famous_for' => 'Management, Data Science, Economics, Linguistics',
                'ar_famous_for' => 'الإدارة، علم البيانات، الاقتصاد، اللغويات',
                'fees' => '£21,000 - £34,000',
                'ar_fees' => 'من 21,000 إلى 34,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 25,
                'name' => 'University of York',
                'slug' => 'university-of-york',
                'country_id' => 1,
                'city_id' => 23,
                'type' => 'public',
                'established_year' => 1964,
                'website' => 'https://www.york.ac.uk',
                'qs_ranking' => 169,
                'the_ranking' => 154,
                'shanghai_ranking' => 201,
                'famous_for' => 'Computer Science, History, Archaeology, Psychology',
                'ar_famous_for' => 'علوم الحاسوب، التاريخ، علم الآثار، علم النفس',
                'fees' => '£21,000 - £36,000',
                'ar_fees' => 'من 21,000 إلى 36,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 26,
                'name' => 'Cardiff University',
                'slug' => 'cardiff-university',
                'country_id' => 1,
                'city_id' => 15,
                'type' => 'public',
                'established_year' => 1963,
                'website' => 'https://www.cardiff.ac.uk',
                'qs_ranking' => 181,
                'the_ranking' => 201,
                'shanghai_ranking' => 201,
                'famous_for' => 'Journalism, Medicine, Architecture, Engineering',
                'ar_famous_for' => 'الصحافة، الطب، العمارة، الهندسة',
                'fees' => '£21,000 - £35,000',
                'ar_fees' => 'من 21,000 إلى 35,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 27,
                'name' => 'University of Reading',
                'slug' => 'university-of-reading',
                'country_id' => 1,
                'city_id' => 27,
                'type' => 'public',
                'established_year' => 1883,
                'website' => 'https://www.reading.ac.uk',
                'qs_ranking' => 194,
                'the_ranking' => 201,
                'shanghai_ranking' => 401,
                'famous_for' => 'Real Estate, Agriculture, Business, Economics',
                'ar_famous_for' => 'العقارات، الزراعة، إدارة الأعمال، الاقتصاد',
                'fees' => '£20,000 - £32,000',
                'ar_fees' => 'من 20,000 إلى 32,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 28,
                'name' => "Queen's University Belfast",
                'slug' => 'queens-university-belfast',
                'country_id' => 1,
                'city_id' => 16,
                'type' => 'public',
                'established_year' => 1926,
                'website' => 'https://www.qub.ac.uk',
                'qs_ranking' => 199,
                'the_ranking' => 198,
                'shanghai_ranking' => 301,
                'famous_for' => 'Engineering, Medicine, Pharmacy, Architecture',
                'ar_famous_for' => 'الهندسة، الطب، الصيدلة، العمارة',
                'fees' => '£20,000 - £34,000',
                'ar_fees' => 'من 20,000 إلى 34,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 29,
                'name' => 'Loughborough University',
                'slug' => 'loughborough-university',
                'country_id' => 1,
                'city_id' => 48,
                'type' => 'public',
                'established_year' => 1907,
                'website' => 'https://www.lboro.ac.uk',
                'qs_ranking' => 225,
                'the_ranking' => 301,
                'shanghai_ranking' => 801,
                'famous_for' => 'Engineering, Sports Science, Design, Business',
                'ar_famous_for' => 'الهندسة، علوم الرياضة، التصميم، إدارة الأعمال',
                'fees' => '£22,000 - £36,000',
                'ar_fees' => 'من 22,000 إلى 36,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 30,
                'name' => 'University of Strathclyde',
                'slug' => 'university-of-strathclyde',
                'country_id' => 1,
                'city_id' => 6,
                'type' => 'public',
                'established_year' => 1796,
                'website' => 'https://www.strath.ac.uk',
                'qs_ranking' => 251,
                'the_ranking' => 351,
                'shanghai_ranking' => 701,
                'famous_for' => 'Engineering, Business, Finance, Architecture',
                'ar_famous_for' => 'الهندسة، إدارة الأعمال، المالية، العمارة',
                'fees' => '£20,000 - £33,000',
                'ar_fees' => 'من 20,000 إلى 33,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 31,
                'name' => 'University of Aberdeen',
                'slug' => 'university-of-aberdeen',
                'country_id' => 1,
                'city_id' => 29,
                'type' => 'public',
                'established_year' => 1495,
                'website' => 'https://www.abdn.ac.uk',
                'qs_ranking' => 262,
                'the_ranking' => 201,
                'shanghai_ranking' => 201,
                'famous_for' => 'Medicine, Law, Engineering, Energy Studies',
                'ar_famous_for' => 'الطب، القانون، الهندسة، دراسات الطاقة',
                'fees' => '£20,000 - £36,000',
                'ar_fees' => 'من 20,000 إلى 36,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 32,
                'name' => 'University of Surrey',
                'slug' => 'university-of-surrey',
                'country_id' => 1,
                'city_id' => 40,
                'type' => 'public',
                'established_year' => 1966,
                'website' => 'https://www.surrey.ac.uk',
                'qs_ranking' => 262,
                'the_ranking' => 201,
                'shanghai_ranking' => 401,
                'famous_for' => 'Hospitality, Tourism, Engineering, Business, Computer Science',
                'ar_famous_for' => 'الضيافة، السياحة، الهندسة، إدارة الأعمال، علوم الحاسوب',
                'fees' => '£21,000 - £35,000',
                'ar_fees' => 'من 21,000 إلى 35,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 33,
                'name' => 'University of Sussex',
                'slug' => 'university-of-sussex',
                'country_id' => 1,
                'city_id' => 19,
                'type' => 'public',
                'established_year' => 1961,
                'website' => 'https://www.sussex.ac.uk',
                'qs_ranking' => 278,
                'the_ranking' => 201,
                'shanghai_ranking' => 201,
                'famous_for' => 'Development Studies, International Relations, Politics, Psychology',
                'ar_famous_for' => 'دراسات التنمية، العلاقات الدولية، السياسة، علم النفس',
                'fees' => '£20,000 - £34,000',
                'ar_fees' => 'من 20,000 إلى 34,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 34,
                'name' => 'Heriot-Watt University',
                'slug' => 'heriot-watt-university',
                'country_id' => 1,
                'city_id' => 7,
                'type' => 'public',
                'established_year' => 1821,
                'website' => 'https://www.hw.ac.uk',
                'qs_ranking' => 287,
                'the_ranking' => 401,
                'shanghai_ranking' => 701,
                'famous_for' => 'Engineering, Architecture, Business, Actuarial Science',
                'ar_famous_for' => 'الهندسة، العمارة، إدارة الأعمال، العلوم الاكتوارية',
                'fees' => '£20,000 - £34,000',
                'ar_fees' => 'من 20,000 إلى 34,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 35,
                'name' => 'Swansea University',
                'slug' => 'swansea-university',
                'country_id' => 1,
                'city_id' => 30,
                'type' => 'public',
                'established_year' => 1920,
                'website' => 'https://www.swansea.ac.uk',
                'qs_ranking' => 292,
                'the_ranking' => 301,
                'shanghai_ranking' => 701,
                'famous_for' => 'Engineering, Law, Computer Science, Materials Science',
                'ar_famous_for' => 'الهندسة، القانون، علوم الحاسوب، علم المواد',
                'fees' => '£19,000 - £32,000',
                'ar_fees' => 'من 19,000 إلى 32,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 36,
                'name' => 'City St Georges, University of London',
                'slug' => 'city-st-georges-university-of-london',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1894,
                'website' => 'https://www.city.ac.uk',
                'qs_ranking' => 310,
                'the_ranking' => 351,
                'shanghai_ranking' => 701,
                'famous_for' => 'Business, Law, Journalism, Health Sciences',
                'ar_famous_for' => 'إدارة الأعمال، القانون، الصحافة، العلوم الصحية',
                'fees' => '£20,000 - £36,000',
                'ar_fees' => 'من 20,000 إلى 36,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 37,
                'name' => 'University of Leicester',
                'slug' => 'university-of-leicester',
                'country_id' => 1,
                'city_id' => 12,
                'type' => 'public',
                'established_year' => 1921,
                'website' => 'https://www.le.ac.uk',
                'qs_ranking' => 326,
                'the_ranking' => 192,
                'shanghai_ranking' => 301,
                'famous_for' => 'Medicine, Genetics, Criminology, Law, Data Science',
                'ar_famous_for' => 'الطب، علم الوراثة، علم الجريمة، القانون، علم البيانات',
                'fees' => '£20,000 - £33,000',
                'ar_fees' => 'من 20,000 إلى 33,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 38,
                'name' => 'Oxford Brookes University',
                'slug' => 'oxford-brookes-university',
                'country_id' => 1,
                'city_id' => 21,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.brookes.ac.uk',
                'qs_ranking' => 374,
                'the_ranking' => 801,
                'shanghai_ranking' => null,
                'famous_for' => 'Architecture, Business, Engineering, Hospitality, Education',
                'ar_famous_for' => 'العمارة، إدارة الأعمال، الهندسة، الضيافة، التعليم',
                'fees' => '£16,000 - £22,000',
                'ar_fees' => 'من 16,000 إلى 22,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 39,
                'name' => 'University of East Anglia',
                'slug' => 'university-of-east-anglia',
                'country_id' => 1,
                'city_id' => 51,
                'type' => 'public',
                'established_year' => 1963,
                'website' => 'https://www.uea.ac.uk',
                'qs_ranking' => 381,
                'the_ranking' => 251,
                'shanghai_ranking' => 301,
                'famous_for' => 'Environmental Science, Development Studies, Creative Writing, Economics, Biology',
                'ar_famous_for' => 'العلوم البيئية، دراسات التنمية، الكتابة الإبداعية، الاقتصاد، الأحياء',
                'fees' => '£19,000 - £33,000',
                'ar_fees' => 'من 19,000 إلى 33,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 40,
                'name' => 'Brunel University London',
                'slug' => 'brunel-university-london',
                'country_id' => 1,
                'city_id' => 58,
                'type' => 'public',
                'established_year' => 1966,
                'website' => 'https://www.brunel.ac.uk',
                'qs_ranking' => 385,
                'the_ranking' => 401,
                'shanghai_ranking' => 601,
                'famous_for' => 'Engineering, Design, Business, Sports Science',
                'ar_famous_for' => 'الهندسة، التصميم، إدارة الأعمال، علوم الرياضة',
                'fees' => '£19,000 - £32,000',
                'ar_fees' => 'من 19,000 إلى 32,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 41,
                'name' => 'Birkbeck, University of London',
                'slug' => 'birkbeck-university-of-london',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1823,
                'website' => 'https://www.bbk.ac.uk',
                'qs_ranking' => 388,
                'the_ranking' => 301,
                'shanghai_ranking' => 801,
                'famous_for' => 'Law, Psychology, Business, Social Sciences',
                'ar_famous_for' => 'القانون، علم النفس، إدارة الأعمال، العلوم الاجتماعية',
                'fees' => '£15,000 - £20,000',
                'ar_fees' => 'من 15,000 إلى 20,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 42,
                'name' => 'Aston University',
                'slug' => 'aston-university',
                'country_id' => 1,
                'city_id' => 3,
                'type' => 'public',
                'established_year' => 1895,
                'website' => 'https://www.aston.ac.uk',
                'qs_ranking' => 395,
                'the_ranking' => 401,
                'shanghai_ranking' => null,
                'famous_for' => 'Business, Finance, Economics, Pharmacy, Engineering',
                'ar_famous_for' => 'إدارة الأعمال، المالية، الاقتصاد، الصيدلة، الهندسة',
                'fees' => '£20,000 - £33,000',
                'ar_fees' => 'من 20,000 إلى 33,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 43,
                'name' => 'University of Kent',
                'slug' => 'university-of-kent',
                'country_id' => 1,
                'city_id' => 34,
                'type' => 'public',
                'established_year' => 1965,
                'website' => 'https://www.kent.ac.uk',
                'qs_ranking' => 397,
                'the_ranking' => 401,
                'shanghai_ranking' => 401,
                'famous_for' => 'Law, Politics, Psychology, Business, International Relations',
                'ar_famous_for' => 'القانون، السياسة، علم النفس، إدارة الأعمال، العلاقات الدولية',
                'fees' => '£18,000 - £32,000',
                'ar_fees' => 'من 18,000 إلى 32,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 44,
                'name' => 'University of Dundee',
                'slug' => 'university-of-dundee',
                'country_id' => 1,
                'city_id' => 37,
                'type' => 'public',
                'established_year' => 1881,
                'website' => 'https://www.dundee.ac.uk',
                'qs_ranking' => 428,
                'the_ranking' => 301,
                'shanghai_ranking' => 301,
                'famous_for' => 'Medicine, Dentistry, Law, Life Sciences, Architecture',
                'ar_famous_for' => 'الطب، طب الأسنان، القانون، علوم الحياة، العمارة',
                'fees' => '£20,000 - £34,000',
                'ar_fees' => 'من 20,000 إلى 34,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 45,
                'name' => 'University of Essex',
                'slug' => 'university-of-essex',
                'country_id' => 1,
                'city_id' => 35,
                'type' => 'public',
                'established_year' => 1964,
                'website' => 'https://www.essex.ac.uk',
                'qs_ranking' => 456,
                'the_ranking' => 301,
                'shanghai_ranking' => 401,
                'famous_for' => 'Politics, Sociology, Economics, Law, Data Analytics',
                'ar_famous_for' => 'السياسة، علم الاجتماع، الاقتصاد، القانون، تحليل البيانات',
                'fees' => '£18,000 - £31,000',
                'ar_fees' => 'من 18,000 إلى 31,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 46,
                'name' => 'Royal Holloway, University of London',
                'slug' => 'royal-holloway-university-of-london',
                'country_id' => 1,
                'city_id' => 39,
                'type' => 'public',
                'established_year' => 1879,
                'website' => 'https://www.rhul.ac.uk',
                'qs_ranking' => 461,
                'the_ranking' => 401,
                'shanghai_ranking' => 801,
                'famous_for' => 'International Relations, Computer Science, Business, Media Arts',
                'ar_famous_for' => 'العلاقات الدولية، علوم الحاسوب، إدارة الأعمال، الفنون الإعلامية',
                'fees' => '£19,000 - £33,000',
                'ar_fees' => 'من 19,000 إلى 33,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 47,
                'name' => 'SOAS University of London',
                'slug' => 'soas-university-of-london',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1916,
                'website' => 'https://www.soas.ac.uk',
                'qs_ranking' => 511,
                'the_ranking' => 401,
                'shanghai_ranking' => null,
                'famous_for' => 'International Relations, Politics, Economics, Asian Studies, African Studies',
                'ar_famous_for' => 'العلاقات الدولية، السياسة، الاقتصاد، الدراسات الآسيوية، الدراسات الإفريقية',
                'fees' => '£19,000 - £28,000',
                'ar_fees' => 'من 19,000 إلى 28,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 48,
                'name' => 'University of Bradford',
                'slug' => 'university-of-bradford',
                'country_id' => 1,
                'city_id' => 14,
                'type' => 'public',
                'established_year' => 1966,
                'website' => 'https://www.bradford.ac.uk',
                'qs_ranking' => 511,
                'the_ranking' => 501,
                'shanghai_ranking' => null,
                'famous_for' => 'Management, Peace Studies, Engineering, Health Sciences',
                'ar_famous_for' => 'الإدارة، دراسات السلام، الهندسة، العلوم الصحية',
                'fees' => '£15,000 - £22,000',
                'ar_fees' => 'من 15,000 إلى 22,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 49,
                'name' => 'University of Stirling',
                'slug' => 'university-of-stirling',
                'country_id' => 1,
                'city_id' => 57,
                'type' => 'public',
                'established_year' => 1967,
                'website' => 'https://www.stir.ac.uk',
                'qs_ranking' => 517,
                'the_ranking' => 501,
                'shanghai_ranking' => 701,
                'famous_for' => 'Sports Science, Education, Aquaculture, Business, Psychology',
                'ar_famous_for' => 'علوم الرياضة، التعليم، الاستزراع المائي، إدارة الأعمال، علم النفس',
                'fees' => '£18,000 - £30,000',
                'ar_fees' => 'من 18,000 إلى 30,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 50,
                'name' => 'University of Huddersfield',
                'slug' => 'university-of-huddersfield',
                'country_id' => 1,
                'city_id' => 42,
                'type' => 'public',
                'established_year' => 1825,
                'website' => 'https://www.hud.ac.uk',
                'qs_ranking' => 524,
                'the_ranking' => 501,
                'shanghai_ranking' => null,
                'famous_for' => 'Engineering, Music, Computing, Business',
                'ar_famous_for' => 'الهندسة، الموسيقى، الحوسبة، إدارة الأعمال',
                'fees' => '£16,000 - £25,000',
                'ar_fees' => 'من 16,000 إلى 25,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 51,
                'name' => 'University of Hull',
                'slug' => 'university-of-hull',
                'country_id' => 1,
                'city_id' => 43,
                'type' => 'public',
                'established_year' => 1927,
                'website' => 'https://www.hull.ac.uk',
                'qs_ranking' => 526,
                'the_ranking' => 501,
                'shanghai_ranking' => 801,
                'famous_for' => 'Logistics, Engineering, Environmental Science, Business',
                'ar_famous_for' => 'الخدمات اللوجستية، الهندسة، العلوم البيئية، إدارة الأعمال',
                'fees' => '£16,000 - £26,000',
                'ar_fees' => 'من 16,000 إلى 26,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 52,
                'name' => 'Northumbria University',
                'slug' => 'northumbria-university',
                'country_id' => 1,
                'city_id' => 10,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.northumbria.ac.uk',
                'qs_ranking' => 550,
                'the_ranking' => 401,
                'shanghai_ranking' => 701,
                'famous_for' => 'Design, Architecture, Business, Law',
                'ar_famous_for' => 'التصميم، العمارة، إدارة الأعمال، القانون',
                'fees' => '£17,000 - £28,000',
                'ar_fees' => 'من 17,000 إلى 28,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 53,
                'name' => 'Coventry University',
                'slug' => 'coventry-university',
                'country_id' => 1,
                'city_id' => 13,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.coventry.ac.uk',
                'qs_ranking' => 558,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Automotive Engineering, Business, Design, Health Sciences',
                'ar_famous_for' => 'هندسة السيارات، إدارة الأعمال، التصميم، العلوم الصحية',
                'fees' => '£16,000 - £27,000',
                'ar_fees' => 'من 16,000 إلى 27,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 54,
                'name' => 'Bangor University',
                'slug' => 'bangor-university',
                'country_id' => 1,
                'city_id' => 32,
                'type' => 'public',
                'established_year' => 1884,
                'website' => 'https://www.bangor.ac.uk',
                'qs_ranking' => 566,
                'the_ranking' => 501,
                'shanghai_ranking' => 501,
                'famous_for' => 'Psychology, Ocean Sciences, Environmental Science, Linguistics',
                'ar_famous_for' => 'علم النفس، علوم المحيطات، العلوم البيئية، اللغويات',
                'fees' => '£16,000 - £26,000',
                'ar_fees' => 'من 16,000 إلى 26,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 55,
                'name' => 'Nottingham Trent University',
                'slug' => 'nottingham-trent-university',
                'country_id' => 1,
                'city_id' => 11,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.ntu.ac.uk',
                'qs_ranking' => 609,
                'the_ranking' => 601,
                'shanghai_ranking' => 801,
                'famous_for' => 'Fashion, Design, Business, Marketing',
                'ar_famous_for' => 'الأزياء، التصميم، إدارة الأعمال، التسويق',
                'fees' => '£16,000 - £28,000',
                'ar_fees' => 'من 16,000 إلى 28,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 56,
                'name' => 'Ulster University',
                'slug' => 'ulster-university',
                'country_id' => 1,
                'city_id' => 16,
                'type' => 'public',
                'established_year' => 1984,
                'website' => 'https://www.ulster.ac.uk',
                'qs_ranking' => 609,
                'the_ranking' => 601,
                'shanghai_ranking' => 801,
                'famous_for' => 'Engineering, Nursing, Computing, Business',
                'ar_famous_for' => 'الهندسة، التمريض، الحوسبة، إدارة الأعمال',
                'fees' => '£15,000 - £26,000',
                'ar_fees' => 'من 15,000 إلى 26,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 57,
                'name' => 'University of Plymouth',
                'slug' => 'university-of-plymouth',
                'country_id' => 1,
                'city_id' => 26,
                'type' => 'public',
                'established_year' => 1862,
                'website' => 'https://www.plymouth.ac.uk',
                'qs_ranking' => 613,
                'the_ranking' => 501,
                'shanghai_ranking' => 701,
                'famous_for' => 'Marine Science, Environmental Science, Nursing, Education',
                'ar_famous_for' => 'العلوم البحرية، العلوم البيئية، التمريض، التعليم',
                'fees' => '£16,000 - £27,000',
                'ar_fees' => 'من 16,000 إلى 27,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 58,
                'name' => 'University of Portsmouth',
                'slug' => 'university-of-portsmouth',
                'country_id' => 1,
                'city_id' => 18,
                'type' => 'public',
                'established_year' => 1870,
                'website' => 'https://www.port.ac.uk',
                'qs_ranking' => 635,
                'the_ranking' => 401,
                'shanghai_ranking' => 901,
                'famous_for' => 'Engineering, Cyber Security, Business, Law',
                'ar_famous_for' => 'الهندسة، الأمن السيبراني، إدارة الأعمال، القانون',
                'fees' => '£17,000 - £28,000',
                'ar_fees' => 'من 17,000 إلى 28,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 59,
                'name' => 'Manchester Metropolitan University',
                'slug' => 'manchester-metropolitan-university',
                'country_id' => 1,
                'city_id' => 2,
                'type' => 'public',
                'established_year' => 1970,
                'website' => 'https://www.mmu.ac.uk',
                'qs_ranking' => 643,
                'the_ranking' => 601,
                'shanghai_ranking' => 601,
                'famous_for' => 'Art, Design, Business, Education, Sports Science',
                'ar_famous_for' => 'الفنون، التصميم، إدارة الأعمال، التعليم، علوم الرياضة',
                'fees' => '£17,000 - £28,000',
                'ar_fees' => 'من 17,000 إلى 28,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 60,
                'name' => 'Kingston University',
                'slug' => 'kingston-university',
                'country_id' => 1,
                'city_id' => 45,
                'type' => 'public',
                'established_year' => 1899,
                'website' => 'https://www.kingston.ac.uk',
                'qs_ranking' => 660,
                'the_ranking' => 801,
                'shanghai_ranking' => null,
                'famous_for' => 'Design, Fashion, Architecture, Business',
                'ar_famous_for' => 'التصميم، الأزياء، العمارة، إدارة الأعمال',
                'fees' => '£16,000 - £26,000',
                'ar_fees' => 'من 16,000 إلى 26,000 جنيه إسترليني سنويًا',
            ],
            [
                'id' => 61,
                'name' => 'Goldsmiths, University of London',
                'slug' => 'goldsmiths-university-of-london',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1891,
                'website' => 'https://www.gold.ac.uk',
                'qs_ranking' => 711,
                'the_ranking' => 501,
                'shanghai_ranking' => null,
                'famous_for' => 'Media, Arts, Sociology, Education',
                'ar_famous_for' => 'الإعلام، الفنون، علم الاجتماع، التربية',
                'fees' => '18000 GBP - 23000 GBP',
                'ar_fees' => '18000 جنيه إسترليني - 23000 جنيه إسترليني',
            ],
            [
                'id' => 62,
                'name' => 'University of the West of England, Bristol',
                'slug' => 'university-of-the-west-of-england-bristol',
                'country_id' => 1,
                'city_id' => 8,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.uwe.ac.uk',
                'qs_ranking' => 721,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Engineering, Architecture, Business, Media',
                'ar_famous_for' => 'الهندسة، العمارة، الأعمال، الإعلام',
                'fees' => '15000 GBP - 19000 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 19000 جنيه إسترليني',
            ],
            [
                'id' => 63,
                'name' => 'Aberystwyth University',
                'slug' => 'aberystwyth-university',
                'country_id' => 1,
                'city_id' => 31,
                'type' => 'public',
                'established_year' => 1872,
                'website' => 'https://www.aber.ac.uk',
                'qs_ranking' => 741,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'International Relations, Agriculture, Geography, History',
                'ar_famous_for' => 'العلاقات الدولية، الزراعة، الجغرافيا، التاريخ',
                'fees' => '15000 GBP - 19000 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 19000 جنيه إسترليني',
            ],
            [
                'id' => 64,
                'name' => 'Bournemouth University',
                'slug' => 'bournemouth-university',
                'country_id' => 1,
                'city_id' => 24,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.bournemouth.ac.uk',
                'qs_ranking' => 801,
                'the_ranking' => 401,
                'shanghai_ranking' => null,
                'famous_for' => 'Media, Film, Animation, Tourism, Marketing',
                'ar_famous_for' => 'الإعلام، السينما، الرسوم المتحركة، السياحة، التسويق',
                'fees' => '16000 GBP - 20000 GBP',
                'ar_fees' => '16000 جنيه إسترليني - 20000 جنيه إسترليني',
            ],
            [
                'id' => 65,
                'name' => 'De Montfort University',
                'slug' => 'de-montfort-university',
                'country_id' => 1,
                'city_id' => 12,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.dmu.ac.uk',
                'qs_ranking' => 801,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Fashion, Design, Business, Computing',
                'ar_famous_for' => 'الأزياء، التصميم، الأعمال، الحوسبة',
                'fees' => '15000 GBP - 18000 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18000 جنيه إسترليني',
            ],
            [
                'id' => 66,
                'name' => 'Keele University',
                'slug' => 'keele-university',
                'country_id' => 1,
                'city_id' => 44,
                'type' => 'public',
                'established_year' => 1962,
                'website' => 'https://www.keele.ac.uk',
                'qs_ranking' => 801,
                'the_ranking' => 501,
                'shanghai_ranking' => null,
                'famous_for' => 'Medicine, Psychology, International Relations, Biology',
                'ar_famous_for' => 'الطب، علم النفس، العلاقات الدولية، الأحياء',
                'fees' => '17000 GBP - 22000 GBP',
                'ar_fees' => '17000 جنيه إسترليني - 22000 جنيه إسترليني',
            ],
            [
                'id' => 67,
                'name' => 'Middlesex University London',
                'slug' => 'middlesex-university-london',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.mdx.ac.uk',
                'qs_ranking' => 801,
                'the_ranking' => 501,
                'shanghai_ranking' => null,
                'famous_for' => 'Business, Law, Computing, Psychology',
                'ar_famous_for' => 'الأعمال، القانون، الحوسبة، علم النفس',
                'fees' => '15000 GBP - 19000 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 19000 جنيه إسترليني',
            ],
            [
                'id' => 68,
                'name' => 'University of Brighton',
                'slug' => 'university-of-brighton',
                'country_id' => 1,
                'city_id' => 19,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.brighton.ac.uk',
                'qs_ranking' => 801,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Art, Design, Architecture, Business, Health',
                'ar_famous_for' => 'الفن، التصميم، العمارة، الأعمال، الصحة',
                'fees' => '15000 GBP - 19000 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 19000 جنيه إسترليني',
            ],
            [
                'id' => 69,
                'name' => 'University of Greenwich',
                'slug' => 'university-of-greenwich',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1890,
                'website' => 'https://www.gre.ac.uk',
                'qs_ranking' => 801,
                'the_ranking' => 601,
                'shanghai_ranking' => 701,
                'famous_for' => 'Engineering, Architecture, Business, Maritime Studies',
                'ar_famous_for' => 'الهندسة، العمارة، الأعمال، الدراسات البحرية',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 70,
                'name' => 'University of Lincoln',
                'slug' => 'university-of-lincoln',
                'country_id' => 1,
                'city_id' => 47,
                'type' => 'public',
                'established_year' => 1996,
                'website' => 'https://www.lincoln.ac.uk',
                'qs_ranking' => 801,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Agriculture, Business, Journalism, Engineering',
                'ar_famous_for' => 'الزراعة، الأعمال، الصحافة، الهندسة',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 71,
                'name' => 'University of Westminster',
                'slug' => 'university-of-westminster',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1838,
                'website' => 'https://www.westminster.ac.uk',
                'qs_ranking' => 801,
                'the_ranking' => 801,
                'shanghai_ranking' => null,
                'famous_for' => 'Media, Film, Fashion, Business',
                'ar_famous_for' => 'الإعلام، السينما، الأزياء، الأعمال',
                'fees' => '16000 GBP - 21000 GBP',
                'ar_fees' => '16000 جنيه إسترليني - 21000 جنيه إسترليني',
            ],
            [
                'id' => 72,
                'name' => 'Edinburgh Napier University',
                'slug' => 'edinburgh-napier-university',
                'country_id' => 1,
                'city_id' => 7,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.napier.ac.uk',
                'qs_ranking' => 851,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Engineering, Computing, Business, Creative Industries',
                'ar_famous_for' => 'الهندسة، الحوسبة، الأعمال، الصناعات الإبداعية',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 73,
                'name' => 'Liverpool John Moores University',
                'slug' => 'liverpool-john-moores-university',
                'country_id' => 1,
                'city_id' => 4,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.ljmu.ac.uk',
                'qs_ranking' => 851,
                'the_ranking' => 501,
                'shanghai_ranking' => 601,
                'famous_for' => 'Engineering, Sports Science, Maritime Studies, Business',
                'ar_famous_for' => 'الهندسة، علوم الرياضة، الدراسات البحرية، الأعمال',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 74,
                'name' => 'London South Bank University',
                'slug' => 'london-south-bank-university',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.lsbu.ac.uk',
                'qs_ranking' => 901,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Engineering, Construction, Business, Health Sciences',
                'ar_famous_for' => 'الهندسة، التشييد، الأعمال، العلوم الصحية',
                'fees' => '15500 GBP - 19500 GBP',
                'ar_fees' => '15500 جنيه إسترليني - 19500 جنيه إسترليني',
            ],
            [
                'id' => 75,
                'name' => 'University of Hertfordshire',
                'slug' => 'university-of-hertfordshire',
                'country_id' => 1,
                'city_id' => 41,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.herts.ac.uk',
                'qs_ranking' => 901,
                'the_ranking' => 601,
                'shanghai_ranking' => 801,
                'famous_for' => 'Engineering, Computer Science, Business, Animation',
                'ar_famous_for' => 'الهندسة، علوم الحاسوب، الأعمال، الرسوم المتحركة',
                'fees' => '15500 GBP - 20000 GBP',
                'ar_fees' => '15500 جنيه إسترليني - 20000 جنيه إسترليني',
            ],
            [
                'id' => 76,
                'name' => 'University of Salford',
                'slug' => 'university-of-salford',
                'country_id' => 1,
                'city_id' => 55,
                'type' => 'public',
                'established_year' => 1967,
                'website' => 'https://www.salford.ac.uk',
                'qs_ranking' => 901,
                'the_ranking' => 801,
                'shanghai_ranking' => null,
                'famous_for' => 'Media, Construction, Business, Health',
                'ar_famous_for' => 'الإعلام، البناء، الأعمال، الصحة',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 77,
                'name' => 'Robert Gordon University (RGU)',
                'slug' => 'robert-gordon-university',
                'country_id' => 1,
                'city_id' => 29,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.rgu.ac.uk',
                'qs_ranking' => 951,
                'the_ranking' => 801,
                'shanghai_ranking' => null,
                'famous_for' => 'Engineering, Business, Architecture, Health Sciences',
                'ar_famous_for' => 'الهندسة، الأعمال، العمارة، العلوم الصحية',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 78,
                'name' => 'Birmingham City University',
                'slug' => 'birmingham-city-university',
                'country_id' => 1,
                'city_id' => 3,
                'type' => 'public',
                'established_year' => 1971,
                'website' => 'https://www.bcu.ac.uk',
                'qs_ranking' => 1001,
                'the_ranking' => 801,
                'shanghai_ranking' => null,
                'famous_for' => 'Art & Design, Media, Business, Engineering',
                'ar_famous_for' => 'الفنون والتصميم، الإعلام، الأعمال، الهندسة',
                'fees' => '15500 GBP - 19500 GBP',
                'ar_fees' => '15500 جنيه إسترليني - 19500 جنيه إسترليني',
            ],
            [
                'id' => 79,
                'name' => 'Glasgow Caledonian University',
                'slug' => 'glasgow-caledonian-university',
                'country_id' => 1,
                'city_id' => 6,
                'type' => 'public',
                'established_year' => 1993,
                'website' => 'https://www.gcu.ac.uk',
                'qs_ranking' => 1001,
                'the_ranking' => 801,
                'shanghai_ranking' => null,
                'famous_for' => 'Business, Nursing, Engineering, Public Health',
                'ar_famous_for' => 'الأعمال، التمريض، الهندسة، الصحة العامة',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 80,
                'name' => 'Leeds Beckett University',
                'slug' => 'leeds-beckett-university',
                'country_id' => 1,
                'city_id' => 5,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.leedsbeckett.ac.uk',
                'qs_ranking' => 1001,
                'the_ranking' => 801,
                'shanghai_ranking' => null,
                'famous_for' => 'Sports Science, Business, Tourism, Media',
                'ar_famous_for' => 'علوم الرياضة، الأعمال، السياحة، الإعلام',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 81,
                'name' => 'London Metropolitan University',
                'slug' => 'london-metropolitan-university',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 2002,
                'website' => 'https://www.londonmet.ac.uk',
                'qs_ranking' => 1001,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Business, Law, Media, Social Sciences',
                'ar_famous_for' => 'الأعمال، القانون، الإعلام، العلوم الاجتماعية',
                'fees' => '15500 GBP - 20000 GBP',
                'ar_fees' => '15500 جنيه إسترليني - 20000 جنيه إسترليني',
            ],
            [
                'id' => 82,
                'name' => 'Sheffield Hallam University',
                'slug' => 'sheffield-hallam-university',
                'country_id' => 1,
                'city_id' => 9,
                'type' => 'public',
                'established_year' => 1843,
                'website' => 'https://www.shu.ac.uk',
                'qs_ranking' => 1001,
                'the_ranking' => 801,
                'shanghai_ranking' => null,
                'famous_for' => 'Engineering, Business, Architecture, Health',
                'ar_famous_for' => 'الهندسة، الأعمال، العمارة، الصحة',
                'fees' => '15500 GBP - 19500 GBP',
                'ar_fees' => '15500 جنيه إسترليني - 19500 جنيه إسترليني',
            ],
            [
                'id' => 83,
                'name' => 'University of East London',
                'slug' => 'university-of-east-london',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.uel.ac.uk',
                'qs_ranking' => 1001,
                'the_ranking' => 1001,
                'shanghai_ranking' => null,
                'famous_for' => 'Sports Science, Psychology, Business, Public Health',
                'ar_famous_for' => 'علوم الرياضة، علم النفس، الأعمال، الصحة العامة',
                'fees' => '15000 GBP - 19000 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 19000 جنيه إسترليني',
            ],
            [
                'id' => 84,
                'name' => 'University of Lancashire',
                'slug' => 'university-of-lancashire',
                'country_id' => 1,
                'city_id' => 54,
                'type' => 'public',
                'established_year' => 1828,
                'website' => 'https://www.uclan.ac.uk',
                'qs_ranking' => 1001,
                'the_ranking' => 1001,
                'shanghai_ranking' => 901,
                'famous_for' => 'Forensic Science, Sports Science, Business, Engineering',
                'ar_famous_for' => 'العلوم الجنائية، علوم الرياضة، الأعمال، الهندسة',
                'fees' => '15500 GBP - 19000 GBP',
                'ar_fees' => '15500 جنيه إسترليني - 19000 جنيه إسترليني',
            ],
            [
                'id' => 85,
                'name' => 'University of Wolverhampton',
                'slug' => 'university-of-wolverhampton',
                'country_id' => 1,
                'city_id' => 59,
                'type' => 'public',
                'established_year' => 1827,
                'website' => 'https://www.wlv.ac.uk',
                'qs_ranking' => 1001,
                'the_ranking' => 801,
                'shanghai_ranking' => null,
                'famous_for' => 'Engineering, Business, Computing, Education',
                'ar_famous_for' => 'الهندسة، الأعمال، الحوسبة، التربية',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 86,
                'name' => 'Canterbury Christ Church University',
                'slug' => 'canterbury-christ-church-university',
                'country_id' => 1,
                'city_id' => 34,
                'type' => 'public',
                'established_year' => 1962,
                'website' => 'https://www.canterbury.ac.uk',
                'qs_ranking' => 1201,
                'the_ranking' => 1201,
                'shanghai_ranking' => null,
                'famous_for' => 'Education, Nursing, Psychology, Theology',
                'ar_famous_for' => 'التربية، التمريض، علم النفس، اللاهوت',
                'fees' => '14000 GBP - 17500 GBP',
                'ar_fees' => '14000 جنيه إسترليني - 17500 جنيه إسترليني',
            ],
            [
                'id' => 87,
                'name' => 'Queen Margaret University',
                'slug' => 'queen-margaret-university',
                'country_id' => 1,
                'city_id' => 7,
                'type' => 'public',
                'established_year' => 1998,
                'website' => 'https://www.qmu.ac.uk',
                'qs_ranking' => 1201,
                'the_ranking' => null,
                'shanghai_ranking' => null,
                'famous_for' => 'Health Sciences, Nursing, Drama, Business',
                'ar_famous_for' => 'العلوم الصحية، التمريض، الدراما، الأعمال',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 88,
                'name' => 'University of Derby',
                'slug' => 'university-of-derby',
                'country_id' => 1,
                'city_id' => 36,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.derby.ac.uk',
                'qs_ranking' => 1201,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Engineering, Education, Business, Health',
                'ar_famous_for' => 'الهندسة، التربية، الأعمال، الصحة',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 89,
                'name' => 'University of Northampton',
                'slug' => 'university-of-northampton',
                'country_id' => 1,
                'city_id' => 52,
                'type' => 'public',
                'established_year' => 2005,
                'website' => 'https://www.northampton.ac.uk',
                'qs_ranking' => 1201,
                'the_ranking' => 1501,
                'shanghai_ranking' => null,
                'famous_for' => 'Business, Education, Computing, Fashion',
                'ar_famous_for' => 'الأعمال، التربية، الحوسبة، الأزياء',
                'fees' => '15000 GBP - 18000 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18000 جنيه إسترليني',
            ],
            [
                'id' => 90,
                'name' => 'Harper Adams University',
                'slug' => 'harper-adams-university',
                'country_id' => 1,
                'city_id' => 50,
                'type' => 'public',
                'established_year' => 1901,
                'website' => 'https://www.harper-adams.ac.uk',
                'qs_ranking' => 1401,
                'the_ranking' => null,
                'shanghai_ranking' => null,
                'famous_for' => 'Agriculture, Agribusiness, Food Technology',
                'ar_famous_for' => 'الزراعة، الأعمال الزراعية، تقنيات الأغذية',
                'fees' => '16000 GBP - 20000 GBP',
                'ar_fees' => '16000 جنيه إسترليني - 20000 جنيه إسترليني',
            ],
            [
                'id' => 91,
                'name' => 'Anglia Ruskin University',
                'slug' => 'anglia-ruskin-university',
                'country_id' => 1,
                'city_id' => 20,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.anglia.ac.uk',
                'qs_ranking' => 1001,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Business, Nursing, Engineering, Psychology',
                'ar_famous_for' => 'الأعمال، التمريض، الهندسة، علم النفس',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 92,
                'name' => 'Cardiff Metropolitan University',
                'slug' => 'cardiff-metropolitan-university',
                'country_id' => 1,
                'city_id' => 15,
                'type' => 'public',
                'established_year' => 1992,
                'website' => 'https://www.cardiffmet.ac.uk',
                'qs_ranking' => 1001,
                'the_ranking' => 1001,
                'shanghai_ranking' => null,
                'famous_for' => 'Sports Science, Business, Education, Health',
                'ar_famous_for' => 'علوم الرياضة، الأعمال، التربية، الصحة',
                'fees' => '14500 GBP - 18000 GBP',
                'ar_fees' => '14500 جنيه إسترليني - 18000 جنيه إسترليني',
            ],
            [
                'id' => 93,
                'name' => 'Cranfield University',
                'slug' => 'cranfield-university',
                'country_id' => 1,
                'city_id' => 33,
                'type' => 'public',
                'established_year' => 1946,
                'website' => 'https://www.cranfield.ac.uk',
                'qs_ranking' => null,
                'the_ranking' => null,
                'shanghai_ranking' => 801,
                'famous_for' => 'Engineering, Aerospace, Manufacturing, Management',
                'ar_famous_for' => 'الهندسة، الطيران والفضاء، التصنيع، الإدارة',
                'fees' => '20000 GBP - 35000 GBP',
                'ar_fees' => '20000 جنيه إسترليني - 35000 جنيه إسترليني',
            ],
            [
                'id' => 94,
                'name' => 'Edge Hill University',
                'slug' => 'edge-hill-university',
                'country_id' => 1,
                'city_id' => 53,
                'type' => 'public',
                'established_year' => 1885,
                'website' => 'https://www.edgehill.ac.uk',
                'qs_ranking' => null,
                'the_ranking' => 1001,
                'shanghai_ranking' => null,
                'famous_for' => 'Education, Nursing, Psychology, Sports Science',
                'ar_famous_for' => 'التربية، التمريض، علم النفس، علوم الرياضة',
                'fees' => '14000 GBP - 17500 GBP',
                'ar_fees' => '14000 جنيه إسترليني - 17500 جنيه إسترليني',
            ],
            [
                'id' => 95,
                'name' => 'Liverpool Hope University',
                'slug' => 'liverpool-hope-university',
                'country_id' => 1,
                'city_id' => 4,
                'type' => 'public',
                'established_year' => 2005,
                'website' => 'https://www.hope.ac.uk',
                'qs_ranking' => null,
                'the_ranking' => 1501,
                'shanghai_ranking' => null,
                'famous_for' => 'Education, Psychology, Humanities, Social Sciences',
                'ar_famous_for' => 'التربية، علم النفس، العلوم الإنسانية، العلوم الاجتماعية',
                'fees' => '13000 GBP - 16000 GBP',
                'ar_fees' => '13000 جنيه إسترليني - 16000 جنيه إسترليني',
            ],
            [
                'id' => 96,
                'name' => 'London School of Hygiene & Tropical Medicine',
                'slug' => 'london-school-of-hygiene-and-tropical-medicine',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1899,
                'website' => 'https://www.lshtm.ac.uk',
                'qs_ranking' => null,
                'the_ranking' => null,
                'shanghai_ranking' => 201,
                'famous_for' => 'Public Health, Epidemiology, Global Health',
                'ar_famous_for' => 'الصحة العامة، علم الوبائيات، الصحة العالمية',
                'fees' => '25000 GBP - 35000 GBP',
                'ar_fees' => '25000 جنيه إسترليني - 35000 جنيه إسترليني',
            ],
            [
                'id' => 97,
                'name' => 'Royal Veterinary College',
                'slug' => 'royal-veterinary-college',
                'country_id' => 1,
                'city_id' => 1,
                'type' => 'public',
                'established_year' => 1791,
                'website' => 'https://www.rvc.ac.uk',
                'qs_ranking' => null,
                'the_ranking' => 501,
                'shanghai_ranking' => 801,
                'famous_for' => 'Veterinary Medicine, Animal Science',
                'ar_famous_for' => 'الطب البيطري، علوم الحيوان',
                'fees' => '27000 GBP - 40000 GBP',
                'ar_fees' => '27000 جنيه إسترليني - 40000 جنيه إسترليني',
            ],
            [
                'id' => 98,
                'name' => 'Scotlands Rural College (SRUC)',
                'slug' => 'scotlands-rural-college-sruc',
                'country_id' => 1,
                'city_id' => 7,
                'type' => 'public',
                'established_year' => 1899,
                'website' => 'https://www.sruc.ac.uk',
                'qs_ranking' => null,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Agriculture, Animal Science, Environmental Science',
                'ar_famous_for' => 'الزراعة، علوم الحيوان، علوم البيئة',
                'fees' => '14000 GBP - 18000 GBP',
                'ar_fees' => '14000 جنيه إسترليني - 18000 جنيه إسترليني',
            ],
            [
                'id' => 99,
                'name' => 'Teesside University',
                'slug' => 'teesside-university',
                'country_id' => 1,
                'city_id' => 49,
                'type' => 'public',
                'established_year' => 1930,
                'website' => 'https://www.tees.ac.uk',
                'qs_ranking' => null,
                'the_ranking' => 601,
                'shanghai_ranking' => null,
                'famous_for' => 'Computing, Digital, Business, Engineering',
                'ar_famous_for' => 'الحوسبة، المجالات الرقمية، الأعمال، الهندسة',
                'fees' => '15000 GBP - 18500 GBP',
                'ar_fees' => '15000 جنيه إسترليني - 18500 جنيه إسترليني',
            ],
            [
                'id' => 100,
                'name' => 'The Open University',
                'slug' => 'the-open-university',
                'country_id' => 1,
                'city_id' => 28,
                'type' => 'public',
                'established_year' => 1969,
                'website' => 'https://www.open.ac.uk',
                'qs_ranking' => null,
                'the_ranking' => 801,
                'shanghai_ranking' => 901,
                'famous_for' => 'Distance Learning, Flexible Study, Open Education',
                'ar_famous_for' => 'التعليم عن بُعد، الدراسة المرنة، التعليم المفتوح',
                'fees' => '7000 GBP - 11000 GBP',
                'ar_fees' => '7000 جنيه إسترليني - 11000 جنيه إسترليني',
            ],
        ];

        University::unguard();
        foreach ($rows as $row) {
            University::updateOrCreate(
                ['id' => $row['id']],
                array_merge([
                    'logo' => null,
                    'cover_image' => null,
                    'is_featured' => false,
                    'is_active' => true,
                ], $row)
            );
        }
        University::reguard();
    }
}
